spring.application.name=simplecd

simplecd.base-dir=C:/SimpleCD
simplecd.workspace-dir=C:/SimpleCD/workspaces
simplecd.logs-dir=C:/SimpleCD/logs
simplecd.artifacts-dir=C:/SimpleCD/artifacts

server.port=8080

simplecd.git.provider-url=https://github.com/jaswantbw
simplecd.git.username=jaswantbw@gmail.com
simplecd.git.password=
simplecd.git.pat=
simplecd.git.ssh-key=