spring.application.name=simplecd

simplecd.base-dir=C:/SimpleCD
simplecd.workspace-dir=C:/SimpleCD/workspaces
simplecd.logs-dir=C:/SimpleCD/logs
simplecd.artifacts-dir=C:/SimpleCD/artifacts

server.port=8080